"""Bake the index surface's thumbnails — ticket 10, the second bake.

    python bake_index.py            # write ../webgl/thumb
    python bake_index.py --check    # measure only, touch nothing

THIS IS A SECOND BAKE, NOT A SECOND WINDOW, AND THAT IS THE WHOLE POINT.

Ticket 03 round 10 budgeted this surface before it existed. Decoded cost is `w x h x 4` off the
file's INTRINSIC dimensions, and CSS scaling does not reduce it — so an index that points at
`../webgl/img/*.webp` and shrinks them in a stylesheet pays the sprite bake's 65.8 MB in full on
the one screen that holds every item at once. It has to own assets cut at its own size.

The cap is derived exactly the way the sprite cap is derived, from the two numbers the page draws
with rather than from taste:

    index.js THUMB_MAX = 80 CSS px, the TALLEST any object is drawn at on the shelf (80 on a
      wide screen, 64 on a phone — the cap is the tallest of them, once)
    gravity.js DPR_CAP = 2, the density the page ever rasterises at

80 x 2 = 160 device px, so a source row above that is fetched, decoded, held, and then thrown
away by the resampler. The sweep asserts the relationship (`thumb_never_exceeds_its_draw`), so
moving either number without re-baking is a red gate rather than a silent 40 MB.

Measured over the real 230: sum of aspect ratios is 273.0, so all 230 resident decode to
160^2 x 4 x 273.0 = 26.7 MB against the 80 MB gate, and 46.4 MB at 01's 400-item ceiling. The
next step up (96 CSS px) is 66.8 MB at 400 items and leaves no room for the scroll's own peak,
which is why 80 is the number.

Nothing is upscaled: a master already under the cap is re-encoded at its own size, same as
bake_sprites.py. Masters live in `img/` and are never touched by either script.
"""

import argparse
import os
import re
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
MASTER = os.path.join(HERE, "img")
OUT = os.path.abspath(os.path.join(HERE, "..", "webgl", "thumb"))
MANIFEST = os.path.abspath(os.path.join(HERE, "..", "webgl", "thumbs.js"))
DATA = os.path.join(HERE, "data.js")

THUMB_PX = 80       # index.js THUMB_MAX
DPR_CAP = 2         # gravity.js fit(): Math.min(devicePixelRatio, 2)
CAP = THUMB_PX * DPR_CAP

# Same encode settings as the sprite bake. Alpha is never lossy — on a page where nothing has an
# edge except the thing itself, the alpha channel IS the asset.
QUALITY = 95
ALPHA_QUALITY = 100
METHOD = 6


def keys():
    """The set the page actually loads, read off data.js rather than off the folder."""
    src = open(DATA, encoding="utf-8").read()
    return re.findall(r'\{k:"([^"]+)"', src)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="measure only, write nothing")
    args = ap.parse_args()

    ks = keys()
    if not ks:
        sys.exit("no keys in data.js")
    os.makedirs(OUT, exist_ok=True)

    dec_master = dec_out = tx_out = 0
    scaled = copied = 0
    missing = []
    tallest = 0
    dims = []

    for k in ks:
        src = os.path.join(MASTER, k + ".webp")
        if not os.path.exists(src):
            missing.append(k)
            continue
        im = Image.open(src)
        im.load()
        w, h = im.size
        dec_master += w * h * 4

        if h > CAP:
            s = CAP / h
            nw, nh = max(1, round(w * s)), CAP
            out = im.convert("RGBA").resize((nw, nh), Image.LANCZOS)
            scaled += 1
        else:
            nw, nh = w, h
            out = im.convert("RGBA")
            copied += 1

        dst = os.path.join(OUT, k + ".webp")
        if not args.check:
            out.save(dst, "WEBP", quality=QUALITY, alpha_quality=ALPHA_QUALITY, method=METHOD)
        dec_out += nw * nh * 4
        tx_out += os.path.getsize(dst) if os.path.exists(dst) else 0
        tallest = max(tallest, nh)
        dims.append((k, nw, nh))

    # The shelf lays itself out from these and never from a loaded image. Two reasons, both
    # structural: the wrap has to be decided before anything is fetched (an index that reflows as
    # 230 photographs arrive is 230 layout shifts), and the no-collision contract is arithmetic
    # over known boxes rather than a race against decode.
    if not args.check:
        with open(MANIFEST, "w", encoding="utf-8") as f:
            f.write("/* GENERATED by bake_index.py — device px of ../webgl/thumb/*.webp.\n"
                    "   The index surface reads its layout out of this and never off a loaded\n"
                    "   image: the wrap is decided before anything is fetched. */\n")
            f.write("window.THUMBS = {\n")
            for k, nw, nh in dims:
                f.write(f'  {k}:[{nw},{nh}],\n')
            f.write("};\n")

    mb = lambda b: b / 1048576
    print(f"{len(ks)} thumbnails   {scaled} downscaled to {CAP}px   {copied} already under the cap")
    if missing:
        print(f"MISSING FROM MASTER ({len(missing)}): {', '.join(missing[:8])}")
    print(f"decoded   masters {mb(dec_master):7.1f} MB -> thumbs {mb(dec_out):7.1f} MB (all resident)")
    print(f"          at 01's 400-item ceiling: {mb(dec_out) * 400 / max(1, len(ks)):.1f} MB")
    print(f"transfer  {mb(tx_out):7.1f} MB")
    print(f"cap       {THUMB_PX}px drawn x dpr {DPR_CAP} = {CAP}px; tallest written {tallest}px")
    if args.check:
        print("(--check: nothing written)")


if __name__ == "__main__":
    main()
