"""PROTOTYPE — regenerate data.js from sourced.json plus the twelve legacy cut-outs.

Hand-maintaining the item list stopped being safe once it passed three dozen. sourced.json is
the record the sourcing passes actually wrote; this turns it into the file the demos read, and
applies the by-eye verdicts from the contact sheet (drops and renames) in one visible place.
"""
import io, json

# thrown out on the contact sheet — wrong object, unreadable cut, or a constraint breach
DROP = {
    "hanfigure":  "washed-out cut, unreadable",
    "barbie":     "returned a cloth purse, not a doll",
    "beetle":     "returned the Porta Nigra, not a car",
    "telegraph":  "scattered parts, unrecognisable",
    "phonograph": "a period engraving of a scene, not an object",
    "armillary":  "returned a blue-and-white dish",
    "shuttle":    "a modern 3D model render — banned, not merely wrong",
    "sputnik":    "cut shredded the antennas; image already deleted",
}

# the search found a real artifact, but not the one the key claimed. name it for what it IS.
RENAME = {
    "gu":          ("Shang ritual wine vessel (jue)", -1200, "c. 1200 BCE"),
    "nataraja":    ("Ardhanarishvara, Chola bronze",   1050, "c. 1050"),
    "dogon":       ("Dogon Aduno Koro vessel",         1700, "c. 1700"),
    "mayavessel":  ("Whistling vessel",                 750, "c. 750 CE"),
    "nes":         ("Super Nintendo",                  1990, "1990"),
    "playstation": ("PlayStation Vita",                2011, "2011"),
    "ipod":        ("iPods",                           2001, "2001"),
}

# the twelve from the first anchor preview; their records live here because they predate sourced.json
LEGACY = [
    dict(k='jar',     y=-2975, disp="3300–2650 BCE", n="Painted jar", src='Cleveland Museum of Art', lic='CC0', cred='Cleveland Museum of Art', url="https://clevelandart.org/art/2004.64"),
    dict(k='indus',   y=-2000, disp="c. 2000 BCE", n="Seal with unicorn", src='Cleveland Museum of Art', lic='CC0', cred='Cleveland Museum of Art', url="https://clevelandart.org/art/1964.104"),
    dict(k='amphora', y=-540,  disp="c. 540 BCE", n="Neck-amphora", src='The Met', lic='CC0', cred='The Met', url="https://www.metmuseum.org/art/collection/search/250551"),
    dict(k='armor',   y=1683,  disp="c. 1683", n="Harquebusier’s armour", src='The Met', lic='CC0', cred='The Met', url="https://www.metmuseum.org/art/collection/search/27792"),
    dict(k='rocket',  y=1829,  disp="1829", n="Stephenson’s Rocket", src='Wikimedia Commons', lic='public domain', cred='Samuel Smiles (engraving)', url="https://commons.wikimedia.org/wiki/File:Rocket_(Smiles).jpg"),
    dict(k='phone',   y=1876,  disp="1876", n="Bell telephone receiver", src='Wikimedia Commons', lic='public domain', cred='C. E. Scribner', url="https://commons.wikimedia.org/wiki/File:Bell_%22iron_box%22_telephone_receiver_1876.jpg"),
    dict(k='bulb',    y=1880,  disp="c. 1880", n="Edison lamps", src='Wikimedia Commons', lic='CC BY-SA 3.0', cred='Richard Warren Lipack', url="https://commons.wikimedia.org/wiki/File:1880EDISON1881LampsSOCKETSrwLIPACKowner.jpg"),
    dict(k='flyer',   y=1903,  disp="1903", n="Wright Flyer", src='Wikimedia Commons', lic='public domain', cred="New Student’s Reference Work", url="https://commons.wikimedia.org/wiki/File:NSRW_Wright_Brothers_Aeroplane.png"),
    dict(k='camera',  y=1930,  disp="c. 1930", n="Kodak Beau Brownie", src='Wikimedia Commons', lic='CC BY-SA 4.0', cred='Cquoi', url="https://commons.wikimedia.org/wiki/File:Kodak_2A_Beau_Brownie.jpg"),
    dict(k='chip',    y=1971,  disp="1971", n="Intel 4004", src='Wikimedia Commons', lic='CC BY-SA 4.0', cred='Al. Struk', url="https://commons.wikimedia.org/wiki/File:4-%D0%B1%D1%96%D1%82%D0%BD%D0%B8%D0%B9_%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D0%BE%D1%80_Intel_4004.jpg"),
    dict(k='neogeo',  y=1994,  disp="1994", n="Neo Geo CD", src='Wikimedia Commons', lic='public domain', cred='Evan-Amos', url="https://commons.wikimedia.org/wiki/File:Neo-Geo-CD-TopLoader-wController-FL.jpg"),
    dict(k='boombox', y=1995,  disp="1990s", n="CD boombox", src='Wikimedia Commons', lic='CC BY 3.0', cred='Andrevruas', url="https://commons.wikimedia.org/wiki/File:AIWA_CSD-ES100_Compact_Disc_Stereo_Radio_Cassette_Recorder_(cropped).jpg"),
]

src = json.load(open("sourced.json", encoding="utf-8"))
rows = list(LEGACY)
for k, d in src.items():
    if k in DROP:
        continue
    name, year, disp = d["name"], d["year"], d["disp"]
    if k in RENAME:
        name, year, disp = RENAME[k]
    rows.append(dict(k=k, y=year, disp=disp, n=name, src=d["src"], lic=d["lic"],
                     cred=d["credit"], url=d["page"]))
rows.sort(key=lambda r: r["y"])

esc = lambda s: (s or "").replace("\\", "\\\\").replace('"', '\\"')
out = io.StringIO()
out.write(f"""/* PROTOTYPE — {len(rows)} real, cited, licence-clean cut-outs. NOT the arrival set (that's 05).
   GENERATED by build_data.py from sourced.json — edit that pipeline, not this file.
   y = absolute year, negative = BCE. disp = the date as the holding institution publishes it. */
window.ITEMS = [
""")
for r in rows:
    out.write(f'  {{k:"{r["k"]}", y:{r["y"]}, disp:"{esc(r["disp"])}", n:"{esc(r["n"])}", '
              f'src:"{esc(r["src"])}", lic:"{esc(r["lic"])}", cred:"{esc(r["cred"])}", '
              f'url:"{esc(r["url"])}"}},\n')
out.write("""];

/* Five movements. Shared across every direction so they are comparable —
   what differs is how each renders a movement, not where the movements fall. */
window.MOVEMENTS = [
  {id:'deep',    from:-9999, to:-500, per:1, title:'the long thin start'},
  {id:'spread',  from:-499,  to:1300, per:2, title:'it starts happening in more places'},
  {id:'trade',   from:1301,  to:1800, per:3, title:'everything reaches everything'},
  {id:'machine', from:1801,  to:1960, per:4, title:'the machine century'},
  {id:'now',     from:1961,  to:9999, per:5, title:'all of it at once'}
];
""")
io.open("data.js", "w", encoding="utf-8").write(out.getvalue())
print(f"data.js: {len(rows)} items  ({len(DROP)} dropped, {len(RENAME)} renamed)")
