"""TICKET 05 — the arrival set. Every row NAMES A SPECIFIC ARTIFACT, never a bare search term.

This is the editorial half of 05; `source5.py` is the mechanical half (acquire, matte, score) and
`build_data.py` is what the site reads. Rows here are candidates: nothing enters the set until it
has been through the matting model AND eyeballed on a contact sheet, because pass 4 proved an
automated top-hit can return a modern 3D render, which is a constraint breach and not merely a
wrong result.

Row = (key, name, year, disp, bucket, region, tier, spec)

  year    absolute, negative = BCE. Epoch stated once: 0 = 1 BCE/1 CE boundary, plain Gregorian.
  disp    the date as written for the visitor; OVERRIDDEN at fetch time by the holding
          institution's own date string wherever the API gives one (source5 records `instdate`
          and flags any candidate whose institution date disagrees with `year` by > 150 years).
  bucket  AFR Africa ex-Egypt · NIL Egypt & Nubia · WCA West & Central Asia · SAS South Asia ·
          EAS East Asia · SEA Southeast Asia · OCE Oceania & Australia · AME Indigenous Americas ·
          EUR Europe · NAM post-1600 settler North America · LAM post-1600 Latin America
  tier    A named on sight by a stranger · B reads as a category on sight · C needs its label
  spec    "src:query|must,words|reject,words"   src = met | com | cma | art

Targets this list was written against are in the ticket, section "Rulings & targets", and were
fixed BEFORE any of these rows existed.
"""

# The 72 already in sourced.json are NOT repeated here. This is the increment.
# Overshoot is deliberate: pass 4 lost 8 of 48 on the contact sheet, so ~15% is budgeted for loss.

ITEMS = [

    # ============================================================ E1  before 3000 BCE
    # A fast prologue by 01's ruling: strength, not volume. Supply is genuinely thinnest here and
    # sub-Saharan Africa has almost no cut-outable object this early — reported, not papered over.
    ("gobekli2",   "Göbekli Tepe pillar",             -9500, "c. 9500 BCE", "WCA", "Turkey",   "A", "com:Göbekli Tepe pillar T-shaped carved|göbekli,gobekli|panorama,aerial,map,plan"),
    ("catalhoyuk", "Seated Woman of Çatalhöyük",      -6000, "c. 6000 BCE", "WCA", "Turkey",   "B", "com:Seated Woman of Catalhoyuk figurine|catalhoyuk,çatalhöyük,seated woman|site,excavation,map"),
    ("halaf",      "Halaf painted bowl",              -5500, "c. 5500 BCE", "WCA", "Syria",    "C", "met:Halaf painted bowl ceramic Syria|bowl,jar"),
    ("vinca",      "Vinča figurine",                  -4500, "c. 4500 BCE", "EUR", "Serbia",   "C", "com:Vinca figurine Neolithic terracotta|vinca,vinča|map,site,culture map"),
    ("varna",      "Varna gold ornament",             -4500, "c. 4500 BCE", "EUR", "Bulgaria", "C", "com:Varna necropolis gold ornament|varna,gold|map,plan"),
    ("cucuteni",   "Cucuteni painted vessel",         -4000, "c. 4000 BCE", "EUR", "Romania",  "C", "met:Cucuteni painted vessel Neolithic|vessel,jar,pot"),
    ("banpo",      "Yangshao painted basin",          -4000, "c. 4000 BCE", "EAS", "China",    "C", "met:Yangshao painted basin Neolithic China earthenware|basin,bowl,jar"),
    ("hongshan",   "Hongshan jade pig-dragon",        -3500, "c. 3500 BCE", "EAS", "China",    "C", "met:Hongshan jade dragon Neolithic China|dragon,jade,pendant"),
    ("eyeidol",    "Tell Brak eye idol",              -3500, "c. 3500 BCE", "WCA", "Syria",    "C", "met:eye idol Tell Brak alabaster|idol,eye"),
    ("naqada",     "Naqada painted jar",              -3500, "c. 3500 BCE", "NIL", "Egypt",    "C", "met:Naqada predynastic painted jar Egypt|jar,vessel"),
    ("narmer",     "Narmer Palette",                  -3100, "c. 3100 BCE", "NIL", "Egypt",    "B", "com:Narmer Palette Egyptian Museum|narmer|drawing,diagram,map"),
    ("otziaxe",    "Ötzi's copper axe",               -3300, "c. 3300 BCE", "EUR", "Alps",     "B", "com:Otzi copper axe Iceman replica museum|axe,beil|body,mummy,tattoo,map"),
    ("valdivia",   "Valdivia figurine",               -3000, "c. 3000 BCE", "AME", "Ecuador",  "C", "art:Valdivia figurine Ecuador|figur"),
    ("mehrgarh",   "Mehrgarh terracotta figurine",    -3000, "c. 3000 BCE", "SAS", "Pakistan", "C", "com:Mehrgarh figurine terracotta|mehrgarh|map,site,plan"),

    # ============================================================ E2  3000 – 500 BCE
    ("stonehenge", "Stonehenge trilithon",            -2500, "c. 2500 BCE", "EUR", "England",  "A", "com:Stonehenge trilithon stones sky|stonehenge|map,plan,diagram,aerial,crowd"),
    ("mycenae",    "Mask of Agamemnon",               -1550, "c. 1550 BCE", "EUR", "Greece",   "A", "com:Mask of Agamemnon gold funeral mask|agamemnon,mask|replica plan,map"),
    ("trundholm",  "Trundholm sun chariot",           -1400, "c. 1400 BCE", "EUR", "Denmark",  "B", "com:Trundholm sun chariot bronze|trundholm,solvogn|coin,stamp,map"),
    ("hammurabi",  "Code of Hammurabi stele",         -1754, "1754 BCE",    "WCA", "Babylon",  "A", "com:Code of Hammurabi stele Louvre|hammurabi|text,map,translation"),
    ("lamassu",    "Assyrian lamassu",                 -710, "c. 710 BCE",  "WCA", "Assyria",  "B", "met:human-headed winged bull lamassu Assyrian|lamassu,winged,bull"),
    ("scythstag",  "Scythian gold stag",               -600, "c. 600 BCE",  "WCA", "Steppe",   "C", "met:Scythian gold stag plaque|stag,deer,plaque"),
    ("pyramidion", "Pyramidion",                      -1850, "c. 1850 BCE", "NIL", "Egypt",    "B", "met:pyramidion limestone Egypt|pyramidion"),
    ("kerma",      "Kerma beaker",                    -1700, "c. 1700 BCE", "NIL", "Nubia",    "C", "met:Kerma beaker Nubia black-topped|beaker,vessel,cup"),
    ("oracle",     "Shang oracle bone",               -1200, "c. 1200 BCE", "EAS", "China",    "B", "com:oracle bone script Shang inscription|oracle bone|chart,table,font,unicode"),
    ("sanxingdui", "Sanxingdui bronze mask",          -1200, "c. 1200 BCE", "EAS", "China",    "B", "com:Sanxingdui bronze mask museum|sanxingdui|map,site,plan"),
    ("dogu",       "Dogū figurine",                   -1000, "c. 1000 BCE", "EAS", "Japan",    "B", "met:Dogu figurine Jomon Japan earthenware|dogu,figure"),
    ("lapita",     "Lapita dentate-stamped pot",      -1000, "c. 1000 BCE", "OCE", "Oceania",  "C", "com:Lapita pottery dentate stamped sherd|lapita|map,migration,chart"),
    ("dongson",    "Đông Sơn bronze drum",             -600, "c. 600 BCE",  "SEA", "Vietnam",  "C", "met:Dong Son bronze drum Vietnam|drum"),
    ("nok",        "Nok terracotta head",              -500, "c. 500 BCE",  "AFR", "Nigeria",  "C", "art:Nok terracotta head Nigeria|head,figur"),
    ("chavin",     "Chavín stirrup vessel",            -900, "c. 900 BCE",  "AME", "Peru",     "C", "art:Chavin Cupisnique stirrup spout bottle|bottle,vessel"),

    # ============================================================ E3  500 BCE – 500 CE
    ("rosetta",    "Rosetta Stone",                    -196, "196 BCE",     "NIL", "Egypt",    "A", "com:Rosetta Stone British Museum|rosetta|replica shop,font,map,text only"),
    ("antikythera","Antikythera mechanism",            -100, "c. 100 BCE",  "EUR", "Greece",   "A", "com:Antikythera mechanism fragment A museum|antikythera|reconstruction model,diagram,scheme,x-ray"),
    ("gundestrup", "Gundestrup cauldron",              -100, "c. 100 BCE",  "EUR", "Denmark",  "B", "com:Gundestrup cauldron silver|gundestrup|map,drawing"),
    ("romanhelmet","Roman cavalry helmet",               50, "c. 50 CE",    "EUR", "Rome",     "B", "met:Roman bronze helmet cavalry|helmet"),
    ("gladius",    "Roman gladius",                      50, "c. 50 CE",    "EUR", "Rome",     "B", "com:Roman gladius sword Mainz museum|gladius,sword|diagram,drawing,map,reenact"),
    ("romanglass", "Roman glass jug",                    200, "c. 200 CE",   "EUR", "Rome",     "C", "met:Roman glass jug blown|jug,bottle,flask"),
    ("vindolanda", "Vindolanda writing tablet",          100, "c. 100 CE",   "EUR", "Britain",  "B", "com:Vindolanda tablet ink writing|vindolanda,tablet|map,fort,site,plan"),
    ("pompeiilamp","Pompeian bronze lamp",                79, "79 CE",       "EUR", "Pompeii",  "C", "met:Roman bronze oil lamp|lamp"),
    ("ashoka",     "Lion Capital of Ashoka",           -250, "c. 250 BCE",  "SAS", "India",    "A", "com:Lion Capital of Ashoka Sarnath museum|lion capital,ashoka|emblem,flag,coat of arms,logo,note"),
    ("amaravati",  "Amaravati relief panel",             200, "c. 200 CE",   "SAS", "India",    "C", "com:Amaravati marble relief panel stupa|amaravati|map,site,plan"),
    ("kushancoin", "Kushan gold coin",                   150, "c. 150 CE",   "SAS", "Kushan",   "C", "met:Kushan gold coin Kanishka|coin,dinar"),
    ("changxin",   "Changxin palace lamp",              -150, "c. 150 BCE",  "EAS", "China",    "B", "com:Changxin palace lamp Han bronze|changxin,palace lamp|map,replica drawing"),
    ("jadesuit",   "Han jade burial suit",              -150, "c. 150 BCE",  "EAS", "China",    "B", "com:jade burial suit Han dynasty museum|jade burial suit,jade suit|map,diagram"),
    ("dotaku",     "Yayoi bronze bell (dōtaku)",         100, "c. 100 CE",   "EAS", "Japan",    "C", "met:dotaku bronze bell Yayoi Japan|bell,dotaku"),
    ("hansilk",    "Han woven silk",                     100, "c. 100 CE",   "EAS", "China",    "C", "met:Han dynasty silk textile fragment woven|silk,textile,fragment"),
    ("paracas",    "Paracas embroidered mantle",        -100, "c. 100 BCE",  "AME", "Peru",     "C", "art:Paracas mantle border embroidered Peru|mantle,textile,border"),
    ("nazcavessel","Nazca polychrome vessel",            200, "c. 200 CE",   "AME", "Peru",     "C", "art:Nazca polychrome vessel Peru|vessel,jar,bottle"),
    ("teotihuacan","Teotihuacan stone mask",             300, "c. 300 CE",   "AME", "Mexico",   "B", "art:Teotihuacan stone mask Mexico|mask"),
    ("hopewell",   "Hopewell mica hand",                 200, "c. 200 CE",   "AME", "Ohio",     "C", "com:Hopewell mica hand Ohio effigy|mica hand,mica|map,mound photo,aerial"),
    ("sasanian",   "Sasanian silver plate",              400, "c. 400 CE",   "WCA", "Iran",     "B", "met:Sasanian silver gilt plate king hunting|plate,dish"),
    ("palmyra",    "Palmyrene funerary bust",            200, "c. 200 CE",   "WCA", "Syria",    "C", "met:Palmyra funerary relief bust limestone|relief,bust,funerary"),
    ("scrolljar",  "Dead Sea Scroll jar",               -100, "c. 100 BCE",  "WCA", "Judea",    "B", "com:Dead Sea Scrolls jar Qumran pottery|scroll jar,qumran jar|cave,site,map,manuscript text"),
    ("aksum",      "Aksumite coin",                      300, "c. 300 CE",   "AFR", "Ethiopia", "C", "com:Aksumite gold coin Ezana Aksum|aksum,axum|map,stele,obelisk"),
    ("linglingo",  "Lingling-o earring",                 100, "c. 100 CE",   "SEA", "Philippines","C","com:lingling-o jade ornament Philippines|lingling|map,chart"),
    ("meroe",      "Meroitic jar",                       100, "c. 100 CE",   "NIL", "Sudan",    "C", "met:Meroitic painted jar Nubia|jar,vessel,cup"),

    # ============================================================ E4  500 – 1500
    ("sutton",     "Sutton Hoo helmet",                  625, "c. 625",      "EUR", "England",  "A", "com:Sutton Hoo helmet British Museum|sutton hoo|replica reconstruction drawing,map,mound,site"),
    ("kells",      "Book of Kells folio",                800, "c. 800",      "EUR", "Ireland",  "B", "com:Book of Kells folio page|kells|font,map,cover photo,building"),
    ("oseberg",    "Oseberg ship's cart",                834, "834",         "EUR", "Norway",   "B", "com:Oseberg cart wagon Viking museum|oseberg|ship photo,map,burial mound,plan"),
    ("bayeux",     "Bayeux Tapestry panel",             1077, "c. 1077",     "EUR", "Normandy", "A", "com:Bayeux Tapestry scene detail|bayeux|museum building,map,town,cathedral"),
    ("stainedglass","Gothic stained-glass panel",       1200, "c. 1200",     "EUR", "France",   "B", "met:stained glass panel Gothic French|panel,glass"),
    ("platearmour","Gothic plate armour",               1450, "c. 1450",     "EUR", "Germany",  "B", "met:armor for man Gothic German steel field|armor,harness"),
    ("gutenberg",  "Gutenberg Bible leaf",              1455, "1455",        "EUR", "Mainz",    "A", "com:Gutenberg Bible page leaf 42-line|gutenberg|museum building,statue,press replica,map"),
    ("venetianglass","Venetian enamelled goblet",       1470, "c. 1470",     "EUR", "Venice",   "C", "met:Venetian enameled goblet glass|goblet,beaker,glass"),
    ("lustrebowl", "Abbasid lustre bowl",                900, "c. 900",      "WCA", "Iraq",     "C", "met:lustre bowl Abbasid Iraq earthenware|bowl,dish"),
    ("incense",    "Seljuk incense burner",             1200, "c. 1200",     "WCA", "Iran",     "C", "met:incense burner bronze Seljuk feline|incense,burner"),
    ("celglobe",   "Islamic celestial globe",           1300, "c. 1300",     "WCA", "Iran",     "C", "met:celestial globe brass inlaid Islamic|globe"),
    ("timurid",    "Timurid jade cup",                  1420, "c. 1420",     "WCA", "Samarkand","C", "com:Ulugh Beg jade cup Timurid|jade cup,ulugh|map,observatory,portrait"),
    ("ruware",     "Ru ware bowl",                      1100, "c. 1100",     "EAS", "China",    "C", "met:Ru ware Song dynasty bowl celadon|bowl,dish,brush washer"),
    ("diamondsutra","Diamond Sutra frontispiece",        868, "868",         "EAS", "Dunhuang", "B", "com:Diamond Sutra 868 frontispiece printed|diamond sutra|cave photo,map,text only"),
    ("jikji",      "Jikji metal-type page",             1377, "1377",        "EAS", "Korea",    "B", "com:Jikji movable metal type Korea page|jikji|monument,stamp,map"),
    ("lacquerbox", "Heian lacquer box",                 1000, "c. 1000",     "EAS", "Japan",    "C", "met:lacquer box maki-e Heian Japan|box,cosmetic"),
    ("palafolio",  "Pala manuscript folio",             1100, "c. 1100",     "SAS", "Bengal",   "C", "met:palm leaf manuscript folio Pala India|folio,manuscript,leaf"),
    ("tarabronze", "Bronze Tara",                        800, "c. 800",      "SAS", "Sri Lanka","B", "com:bronze Tara Sri Lanka British Museum|tara|map,temple,painting"),
    ("borobudur",  "Borobudur relief block",             800, "c. 800",      "SEA", "Java",     "B", "com:Borobudur relief panel ship carving|borobudur|aerial,panorama,map,plan,sunrise"),
    ("khmerbronze","Khmer bronze deity",                1150, "c. 1150",     "SEA", "Cambodia", "B", "met:Khmer bronze Angkor deity Cambodia|figure,buddha,deity,vishnu"),
    ("kris",       "Javanese kris",                     1400, "c. 1400",     "SEA", "Java",     "C", "met:kris dagger Java hilt|kris,dagger,knife"),
    ("igboukwu",   "Igbo-Ukwu roped pot",                950, "c. 950",      "AFR", "Nigeria",  "B", "com:Igbo-Ukwu bronze roped pot|igbo-ukwu,igbo ukwu|map,site,excavation"),
    ("zimbird",    "Great Zimbabwe soapstone bird",     1300, "c. 1300",     "AFR", "Zimbabwe", "B", "com:Great Zimbabwe soapstone bird|zimbabwe bird,soapstone bird|ruins,wall,aerial,flag,coat of arms"),
    ("ifehead",    "Ife bronze head",                   1300, "c. 1300",     "AFR", "Nigeria",  "A", "com:Ife bronze head Yoruba Nigeria|ife head,ife bronze|map,town,king photo"),
    ("djenne",     "Djenné equestrian figure",          1200, "c. 1200",     "AFR", "Mali",     "C", "art:Djenne equestrian terracotta Mali|equestrian,figur,horse"),
    ("ethcross",   "Ethiopian processional cross",      1400, "c. 1400",     "AFR", "Ethiopia", "B", "met:Ethiopian processional cross|cross"),
    ("incallama",  "Inca gold llama figurine",          1450, "c. 1450",     "AME", "Peru",     "B", "com:Inca gold llama figurine silver alloy|llama|map,animal photo,ruins"),
    ("gorget",     "Mississippian shell gorget",        1200, "c. 1200",     "AME", "Tennessee","C", "art:Mississippian shell gorget engraved|gorget,shell"),
    ("puebloan",   "Ancestral Puebloan jar",            1100, "c. 1100",     "AME", "Southwest","C", "art:Ancestral Pueblo black-on-white jar Mimbres|jar,bowl,olla"),
    ("chacmool",   "Chacmool figure",                   1000, "c. 1000",     "AME", "Yucatán",  "B", "com:Chacmool sculpture Chichen Itza museum|chacmool,chac mool|pyramid,map,ruins,aerial"),
    ("heitiki",    "Hei-tiki pendant",                  1400, "c. 1400",     "OCE", "Aotearoa", "B", "met:hei-tiki nephrite pendant Maori|tiki,pendant"),
    ("moai2",      "Moai head",                         1300, "c. 1300",     "OCE", "Rapa Nui", "A", "com:moai statue British Museum Hoa Hakananai|moai,hoa haka|island landscape,map,sunset,row of,panorama"),
    ("fatimid",    "Fatimid rock-crystal ewer",         1000, "c. 1000",     "NIL", "Egypt",    "C", "com:Fatimid rock crystal ewer|rock crystal ewer|map,mosque"),

    # ============================================================ E5  1500 – 1800
    ("mercator",   "Mercator terrestrial globe",        1541, "1541",        "EUR", "Flanders", "B", "com:Mercator globe 1541 terrestrial|mercator|portrait,map sheet,projection,atlas page"),
    ("durerblock", "Dürer woodblock print",             1515, "1515",        "EUR", "Nuremberg","B", "com:Durer Rhinoceros woodcut 1515|rhinoceros,dürer,durer|portrait,stamp,coin"),
    ("wheellock",  "Wheellock pistol",                  1580, "c. 1580",     "EUR", "Germany",  "B", "met:wheellock pistol German|pistol"),
    ("newtontel",  "Newton's reflecting telescope",     1668, "1668",        "EUR", "England",  "A", "com:Newton reflecting telescope replica Royal Society|newton|portrait,statue,apple,book,prism diagram"),
    ("microscope", "Early compound microscope",         1670, "c. 1670",     "EUR", "Netherlands","B","com:Leeuwenhoek microscope replica brass|microscope|portrait,drawing,diagram,cell"),
    ("pocketwatch","Pair-case pocket watch",            1650, "c. 1650",     "EUR", "England",  "B", "met:pair case watch verge gilt|watch"),
    ("delft",      "Delft tulip vase",                  1690, "c. 1690",     "EUR", "Netherlands","C","met:Delft tulip vase pyramid faience|vase,flower"),
    ("meissen",    "Meissen porcelain figure",          1750, "c. 1750",     "EUR", "Saxony",   "C", "met:Meissen porcelain figure Kaendler|figure,group"),
    ("sextant",    "Sextant",                           1760, "c. 1760",     "EUR", "England",  "B", "met:sextant brass navigation instrument|sextant,octant"),
    ("h4",         "Harrison's H4 sea watch",           1761, "1761",        "EUR", "England",  "A", "com:Harrison H4 marine chronometer watch|h4,harrison|portrait,h1,h2,h3,diagram,stamp"),
    ("wattengine", "Watt beam engine",                  1776, "1776",        "EUR", "Scotland", "A", "com:Watt beam steam engine museum preserved|watt,beam engine|portrait,statue,diagram,drawing,patent"),
    ("spinjenny",  "Spinning jenny",                    1764, "c. 1764",     "EUR", "England",  "B", "com:spinning jenny machine museum|jenny|portrait,drawing,diagram,mill photo"),
    ("encyclopedie","Encyclopédie plate",               1751, "1751",        "EUR", "France",   "B", "com:Encyclopedie Diderot plate engraving|encyclopedie,encyclopédie|title page,portrait,bust"),
    ("brownbess",  "Flintlock musket",                  1750, "c. 1750",     "EUR", "England",  "B", "met:flintlock musket military|musket,gun"),
    ("celglobe2",  "Celestial globe on stand",          1600, "c. 1600",     "EUR", "Netherlands","B","met:celestial globe stand engraved|globe"),
    ("claypipe",   "Clay tobacco pipe",                 1650, "c. 1650",     "EUR", "England",  "C", "com:clay tobacco pipe 17th century archaeology|clay pipe,tobacco pipe|shop,advert,map,smoking man"),
    ("iznik",      "Iznik dish",                        1560, "c. 1560",     "WCA", "Ottoman",  "B", "met:Iznik dish stonepaste Ottoman|dish,plate"),
    ("safavid",    "Safavid carpet",                    1550, "c. 1550",     "WCA", "Iran",     "B", "met:Safavid carpet Persian silk wool|carpet,rug"),
    ("turbanhelm", "Ottoman turban helmet",             1500, "c. 1500",     "WCA", "Ottoman",  "C", "met:turban helmet Ottoman steel|helmet"),
    ("tughra",     "Ottoman tughra",                    1555, "c. 1555",     "WCA", "Ottoman",  "C", "met:tughra Suleiman illuminated|tughra"),
    ("shahjahan",  "Shah Jahan's jade wine cup",        1657, "1657",        "SAS", "Mughal",   "B", "com:Shah Jahan jade wine cup Victoria Albert|jade cup,wine cup|portrait,miniature,throne,taj"),
    ("mughalmini", "Mughal album page",                 1620, "c. 1620",     "SAS", "Mughal",   "C", "met:Mughal album page painting Jahangir|folio,page,portrait"),
    ("talwar",     "Talwar sword",                      1700, "c. 1700",     "SAS", "India",    "C", "met:talwar sword Indian hilt|sword,talwar"),
    ("chintz",     "Indian chintz palampore",           1700, "c. 1700",     "SAS", "Coromandel","C","met:palampore chintz painted cotton India|palampore,chintz"),
    ("moonjar",    "Korean moon jar",                   1700, "c. 1700",     "EAS", "Korea",    "B", "met:moon jar Joseon white porcelain Korea|jar"),
    ("tanegashima","Tanegashima matchlock",             1600, "c. 1600",     "EAS", "Japan",    "C", "met:Japanese matchlock gun tanegashima|gun,matchlock,barrel"),
    ("rakubowl",   "Raku tea bowl",                     1600, "c. 1600",     "EAS", "Japan",    "C", "met:raku tea bowl chawan Japan|bowl,chawan"),
    ("kesi",       "Chinese kesi silk robe",            1600, "c. 1600",     "EAS", "China",    "C", "met:kesi silk tapestry robe Chinese|robe,kesi,panel"),
    ("snuffbottle","Qing snuff bottle",                 1750, "c. 1750",     "EAS", "China",    "C", "met:snuff bottle Qing glass jade|snuff"),
    ("thaibuddha", "Ayutthaya Buddha head",             1600, "c. 1600",     "SEA", "Siam",     "C", "met:Buddha head Ayutthaya Thailand bronze|buddha,head"),
    ("vietblue",   "Vietnamese blue-and-white dish",    1500, "c. 1500",     "SEA", "Vietnam",  "C", "met:Vietnamese blue and white dish|dish,bowl,jar"),
    ("goldweight", "Akan gold weight",                  1700, "c. 1700",     "AFR", "Ghana",    "C", "art:Akan goldweight brass Ghana|weight,goldweight"),
    ("nkisi",      "Kongo nkisi power figure",          1700, "c. 1700",     "AFR", "Kongo",    "B", "met:power figure nkisi nkondi Kongo|power figure,nkisi"),
    ("ethicon",    "Ethiopian painted icon",            1600, "c. 1600",     "AFR", "Ethiopia", "C", "met:Ethiopian icon diptych painted panel|icon,diptych,panel"),
    ("wampum",     "Wampum belt",                       1700, "c. 1700",     "AME", "Haudenosaunee","B","com:wampum belt beads Iroquois museum|wampum|map,treaty text,drawing,portrait"),
    ("pieceof8",   "Spanish piece of eight",            1600, "c. 1600",     "LAM", "Potosí",   "B", "com:Spanish colonial eight reales cob silver coin|reales,piece of eight,cob|map,mine,portrait,banknote"),
    ("talavera",   "Puebla talavera jar",               1700, "c. 1700",     "LAM", "Mexico",   "C", "met:Talavera Puebla jar tin-glazed Mexico|jar,vase,basin"),
    ("reveretea",  "Revere silver teapot",              1770, "c. 1770",     "NAM", "Boston",   "B", "met:Paul Revere silver teapot|teapot,pot"),
    ("windsor",    "Windsor chair",                     1760, "c. 1760",     "NAM", "Colonies", "C", "met:Windsor armchair American wood|chair"),
    ("dunlap",     "Declaration of Independence broadside",1776,"1776",      "NAM", "Philadelphia","A","com:Dunlap broadside Declaration of Independence 1776|dunlap,declaration|painting,signing,memorial,statue,building"),
    ("ahuula",     "Hawaiian feather cloak",            1780, "c. 1780",     "OCE", "Hawaiʻi",  "B", "met:Hawaiian feather cloak ahu ula|cloak,cape"),
    ("wakahuia",   "Waka huia treasure box",            1700, "c. 1700",     "OCE", "Aotearoa", "C", "met:waka huia treasure box Maori carved|box,waka"),

    # ============================================================ E6  1800 – 1900
    ("daguerreo",  "Daguerreotype camera",              1839, "1839",        "EUR", "France",   "A", "com:Giroux daguerreotype camera 1839|daguerreotype camera,giroux|portrait,plate,image of,building"),
    ("singer",     "Singer sewing machine",             1851, "c. 1851",     "EUR", "New York", "A", "com:Singer sewing machine antique treadle|singer|advert,poster,logo,factory,building,trade card"),
    ("benz",       "Benz Patent-Motorwagen",            1886, "1886",        "EUR", "Germany",  "A", "com:Benz Patent Motorwagen 1886 replica museum|motorwagen,patent-motorwagen|portrait,patent drawing,logo,stamp"),
    ("kodak1",     "Kodak No. 1 camera",                1888, "1888",        "NAM", "Rochester","A", "com:Kodak No 1 box camera 1888|kodak no,kodak original|advert,poster,logo,film,building"),
    ("gramophone", "Berliner gramophone",               1889, "c. 1889",     "EUR", "Germany",  "A", "com:Berliner gramophone disc machine museum|gramophone,grammophon|logo,advert,dog,record label"),
    ("cinematog",  "Lumière Cinématographe",            1895, "1895",        "EUR", "France",   "A", "com:Lumiere Cinematographe camera 1895|cinematograph,cinématographe|poster,portrait,film still,building"),
    ("marconi",    "Marconi wireless set",              1897, "c. 1897",     "EUR", "England",  "B", "com:Marconi wireless telegraph apparatus museum|marconi|portrait,station photo,mast,map,stamp"),
    ("xraytube",   "Crookes X-ray tube",                1896, "c. 1896",     "EUR", "Germany",  "B", "com:Crookes X-ray tube early|tube|hand,radiograph,portrait,diagram"),
    ("dieselengine","Diesel engine",                    1897, "1897",        "EUR", "Germany",  "B", "com:Diesel engine 1897 museum first|diesel engine,dieselmotor|portrait,truck,car,logo,ship"),
    ("safetybike", "Safety bicycle",                    1885, "c. 1885",     "EUR", "England",  "A", "com:Rover safety bicycle 1885 museum|safety bicycle,rover|advert,poster,map,portrait"),
    ("braille",    "Braille slate and stylus",          1829, "c. 1829",     "EUR", "France",   "B", "com:braille slate stylus writing frame|braille slate,braille frame|alphabet chart,portrait,sign,book cover"),
    ("stethoscope","Wooden stethoscope",                1816, "c. 1816",     "EUR", "France",   "B", "com:Laennec wooden stethoscope monaural|stethoscope|portrait,painting,modern,diagram"),
    ("davylamp",   "Davy lamp",                         1815, "1815",        "EUR", "England",  "B", "com:Davy lamp miners safety lamp|davy lamp,safety lamp|portrait,diagram,memorial"),
    ("cablesample","Atlantic cable section",            1858, "1858",        "EUR", "Atlantic", "B", "com:Atlantic telegraph cable specimen section 1858|cable|map,ship,route,portrait,stamp"),
    ("swissknife", "Swiss Army knife",                  1891, "1891",        "EUR", "Switzerland","A","com:Victorinox Swiss Army knife soldier|swiss army knife,victorinox|logo,advert,shop,giant"),
    ("teslacoil",  "Tesla coil",                        1891, "c. 1891",     "EUR", "New York", "B", "com:Tesla coil apparatus museum original|tesla coil|portrait,lightning show,modern,diagram"),
    ("morsekey2",  "Telegraph key",                     1844, "c. 1844",     "NAM", "Washington","B", "com:telegraph key brass sounder instrument museum|telegraph key,morse key|code chart,diagram,portrait,line,pole,alphabet"),
    ("barbedwire", "Barbed wire",                       1874, "1874",        "NAM", "Illinois", "B", "com:barbed wire patent samples Glidden strand|barbed wire|fence photo,cow,field,border,war,map"),
    ("winchester", "Winchester repeating rifle",        1873, "1873",        "NAM", "Connecticut","A","com:Winchester Model 1873 rifle museum|winchester|advert,poster,house,logo,cartridge box"),
    ("gatling",    "Gatling gun",                       1862, "1862",        "NAM", "Indiana",  "A", "com:Gatling gun museum original carriage|gatling|portrait,drawing,patent,modern minigun"),
    ("levis",      "Levi's riveted jeans",              1873, "1873",        "NAM", "San Francisco","A","com:Levi Strauss 501 riveted jeans vintage|levi,jeans|logo,store,advert,portrait,patch only"),
    ("masonjar",   "Mason jar",                         1858, "1858",        "NAM", "New Jersey","B", "com:Mason jar zinc lid antique canning|mason jar|logo,advert,modern craft,drink"),
    ("edisonphono","Edison cylinder phonograph",        1877, "c. 1877",     "NAM", "New Jersey","A","com:Edison phonograph cylinder machine museum|phonograph|advert,poster,patent,portrait,cylinder box,building"),
    ("tiffanylamp","Tiffany leaded-glass lamp",         1899, "c. 1899",     "NAM", "New York", "A", "met:Tiffany leaded glass table lamp|lamp"),
    ("cornflakes", "Corn flakes carton",                1898, "c. 1898",     "NAM", "Michigan", "B", "com:Kellogg corn flakes early box package|corn flakes,kellogg|advert,factory,portrait,modern box,logo"),
    ("greatwave",  "The Great Wave off Kanagawa",       1831, "c. 1831",     "EAS", "Japan",    "A", "met:Great Wave off Kanagawa Hokusai woodblock|wave,kanagawa"),
    ("cloisonne",  "Meiji cloisonné vase",              1880, "c. 1880",     "EAS", "Japan",    "C", "met:Japanese cloisonne vase Meiji|vase"),
    ("rickshaw",   "Jinrikisha",                        1870, "c. 1870",     "EAS", "Japan",    "B", "com:jinrikisha rickshaw antique museum vehicle|rickshaw,jinrikisha|street scene,crowd,modern,tourist,map"),
    ("qingrobe",   "Qing dragon robe",                  1850, "c. 1850",     "EAS", "China",    "C", "met:Qing dynasty dragon robe silk chaofu|robe"),
    ("kashmir",    "Kashmir shawl",                     1850, "c. 1850",     "SAS", "Kashmir",  "C", "met:Kashmir shawl woven wool India|shawl"),
    ("hookah",     "Indian hookah base",                1850, "c. 1850",     "SAS", "India",    "C", "met:hookah base bidri silver India|hookah,huqqa"),
    ("zulushield", "Zulu shield",                       1879, "c. 1879",     "AFR", "Zululand", "B", "met:Zulu shield hide isihlangu|shield"),
    ("asantegold", "Asante gold ornament",              1874, "c. 1874",     "AFR", "Ghana",    "C", "met:Asante gold ornament Ghana pendant|ornament,pendant,disk"),
    ("lakotamocs", "Lakota beaded moccasins",           1880, "c. 1880",     "AME", "Plains",   "B", "art:Lakota beaded moccasins Plains|moccasin"),
    ("navajoblanket","Navajo chief's blanket",          1860, "c. 1860",     "AME", "Diné",     "B", "art:Navajo chief blanket wearing|blanket,serape"),
    ("argillite",  "Haida argillite carving",           1870, "c. 1870",     "AME", "Haida Gwaii","C","art:Haida argillite carving pipe panel|argillite,pipe,panel"),
    ("fez",        "Ottoman fez",                       1830, "c. 1830",     "WCA", "Ottoman",  "B", "met:fez Ottoman felt cap|fez,cap"),
    ("abshield",   "Aboriginal parrying shield",        1850, "c. 1850",     "OCE", "Australia","C", "com:Aboriginal parrying shield Australia museum|shield|map,flag,rock art,painting,modern"),

    # ============================================================ E7  1900 – 1960
    ("wagenfeld",  "Bauhaus table lamp",                1924, "1924",        "EUR", "Weimar",   "B", "com:Wagenfeld Bauhaus table lamp WG24|wagenfeld,bauhaus lamp|building,logo,poster,portrait"),
    ("wassily",    "Wassily chair",                     1925, "1925",        "EUR", "Dessau",   "B", "com:Wassily chair Breuer B3 tubular steel|wassily,breuer|portrait,building,logo"),
    ("anglepoise", "Anglepoise lamp",                   1932, "1932",        "EUR", "England",  "B", "com:Anglepoise lamp 1227 original|anglepoise|logo,advert,modern led,shop"),
    ("spitfire",   "Supermarine Spitfire",              1936, "1936",        "EUR", "England",  "A", "com:Spitfire aircraft museum static preserved|spitfire|formation,flight,sky,cockpit only,model kit,memorial"),
    ("v2",         "V-2 rocket",                        1944, "1944",        "EUR", "Germany",  "A", "com:V-2 rocket museum display vertical|v-2,v2 rocket,a4 rocket|launch,diagram,portrait,map,factory"),
    ("tubemap",    "London Underground diagram",        1933, "1933",        "EUR", "London",   "A", "com:Beck London Underground map 1933 diagram|underground map,tube map,beck|modern map,station,platform,sign,roundel"),
    ("penicillin", "Penicillin culture vessel",         1928, "1928",        "EUR", "London",   "A", "com:Fleming penicillin mould culture dish original|penicillin,fleming|portrait,statue,stamp,pill,modern"),
    ("mini",       "Mini",                              1959, "1959",        "EUR", "England",  "A", "com:Mini Morris 1959 classic car museum|mini|cooper rally,modern,logo,interior,engine"),
    ("ak47",       "AK-47",                             1947, "1947",        "EUR", "USSR",     "A", "com:AK-47 type 2 rifle museum display|ak-47,avtomat,kalashnikov|flag,portrait,soldier,logo,drawing"),
    ("sputnik2",   "Sputnik 1",                         1957, "1957",        "EUR", "USSR",     "A", "com:Sputnik 1 replica museum satellite sphere|sputnik|stamp,launch,diagram,portrait,map,monument"),
    ("vwbeetle",   "Volkswagen Type 1",                 1938, "1938",        "EUR", "Germany",  "A", "com:Volkswagen Type 1 Beetle car side view museum|volkswagen,beetle,käfer|logo,factory,interior,engine,advert,modern"),
    ("bakelite",   "Bakelite radio",                    1934, "c. 1934",     "EUR", "England",  "A", "com:Ekco AD65 bakelite radio round|bakelite radio,ad65,ekco|advert,logo,interior,valve"),
    ("bairdtv",    "Early television receiver",         1936, "c. 1936",     "EUR", "London",   "A", "com:early television receiver 1930s set museum|television,televisor|studio,camera,portrait,modern,advert"),
    ("citroen2cv", "Citroën 2CV",                       1948, "1948",        "EUR", "France",   "B", "com:Citroen 2CV car museum side|2cv|logo,interior,engine,rally,modern"),
    ("transistor", "Point-contact transistor",          1947, "1947",        "NAM", "New Jersey","A","com:first transistor replica Bell Labs 1947|transistor|diagram,portrait,modern chip,logo,symbol"),
    ("eniac",      "ENIAC panel",                       1946, "1946",        "NAM", "Philadelphia","A","com:ENIAC computer panel museum unit|eniac|portrait,diagram,building,plaque"),
    ("fatman",     "Fat Man casing",                    1945, "1945",        "NAM", "New Mexico","A","com:Fat Man bomb casing museum replica|fat man,mk-3|cloud,explosion,portrait,map,diagram"),
    ("jeep",       "Willys Jeep",                       1941, "1941",        "NAM", "Ohio",     "A", "com:Willys MB Jeep military vehicle museum|willys,jeep|modern,logo,advert,interior,convoy"),
    ("monopoly",   "Monopoly set",                      1935, "1935",        "NAM", "Pennsylvania","A","com:Monopoly board game 1935 vintage set|monopoly|logo,modern edition,advert,shop,cartoon"),
    ("slinky",     "Slinky",                            1945, "1945",        "NAM", "Pennsylvania","A","com:Slinky spring toy metal|slinky|logo,advert,cartoon,modern plastic"),
    ("tupperware", "Tupperware container",              1946, "c. 1946",     "NAM", "Massachusetts","B","com:Tupperware container vintage plastic bowl|tupperware|party,advert,logo,modern"),
    ("landcamera", "Polaroid Land Camera",              1948, "1948",        "NAM", "Massachusetts","A","com:Polaroid Land Camera Model 95 vintage|land camera,polaroid|logo,advert,photo print,portrait,modern"),
    ("strat",      "Fender Stratocaster",               1954, "1954",        "NAM", "California","A", "com:Fender Stratocaster 1950s sunburst guitar|stratocaster|logo,advert,player,headstock only,pedal"),
    ("chucktaylor","Converse All Star",                 1917, "c. 1917",     "NAM", "Massachusetts","A","com:Converse Chuck Taylor All Star canvas shoe|converse,chuck taylor,all star|logo,advert,store,painting"),
    ("teddybear",  "Teddy bear",                        1903, "c. 1903",     "NAM", "New York", "A", "com:early teddy bear mohair 1900s museum|teddy bear|cartoon,advert,logo,modern,pile of"),
    ("dc3",        "Douglas DC-3",                      1935, "1935",        "NAM", "California","A", "com:Douglas DC-3 aircraft museum static side|dc-3,c-47,dakota|flight,formation,cockpit,interior,model,poster"),
    ("zero",       "Mitsubishi A6M Zero",               1940, "1940",        "EAS", "Japan",    "A", "com:Mitsubishi A6M Zero aircraft museum static|a6m,zero fighter|flight,formation,cockpit,model,diagram"),
    ("nikonS",     "Nikon rangefinder camera",          1948, "1948",        "EAS", "Japan",    "B", "com:Nikon S rangefinder camera 1950s|nikon s,nikon m,nikon rangefinder|logo,advert,modern dslr,lens only"),
    ("supercub",   "Honda Super Cub",                   1958, "1958",        "EAS", "Japan",    "A", "com:Honda Super Cub C100 1958 motorcycle|super cub,c100|logo,advert,modern,crowd,street"),
    ("maosuit",    "Zhongshan suit",                    1950, "c. 1950",     "EAS", "China",    "B", "com:Zhongshan suit Mao jacket museum garment|zhongshan,mao suit|portrait,poster,statue,crowd,badge"),
    ("charkha",    "Charkha spinning wheel",            1930, "c. 1930",     "SAS", "India",    "A", "com:charkha spinning wheel Gandhi museum box|charkha|portrait,statue,stamp,flag,note,logo"),
    ("ambassador", "Hindustan Ambassador",              1958, "1958",        "SAS", "India",    "B", "com:Hindustan Ambassador car side view|ambassador|logo,taxi crowd,interior,street scene"),
    ("kente",      "Kente cloth",                       1957, "c. 1957",     "AFR", "Ghana",    "B", "met:kente cloth Asante strip woven Ghana|kente,cloth,wrapper"),
    ("boomerang",  "Returning boomerang",               1930, "c. 1930",     "OCE", "Australia","C", "com:returning boomerang wooden Australia museum|boomerang|souvenir shop,logo,modern plastic,diagram,painting"),
    ("inuitcarve", "Inuit soapstone carving",           1955, "c. 1955",     "AME", "Nunavut",  "C", "art:Inuit soapstone carving sculpture|carving,figure,bear,sculpture"),

    # ============================================================ E8  1960 – now
    ("apollosuit", "Apollo A7L pressure suit",          1969, "1969",        "NAM", "Delaware", "A", "com:Apollo A7L spacesuit museum display Smithsonian|a7l,spacesuit,space suit|3d,render,model,moon surface,launch,portrait"),
    ("f1engine",   "Saturn V F-1 engine",               1967, "1967",        "NAM", "Alabama",  "A", "com:F-1 rocket engine museum display Saturn V|f-1 engine,f1 rocket engine|launch,diagram,render,3d,assembly line"),
    ("container",  "Intermodal shipping container",     1968, "1968",        "NAM", "New Jersey","A","com:shipping container ISO corten single isolated|container|ship,port,stack,crane,map,house,3d,render"),
    ("b747",       "Boeing 747",                        1969, "1969",        "NAM", "Washington","A", "com:Boeing 747 aircraft museum static side|747|flight,cockpit,interior,model,diagram,logo"),
    ("goldenrec",  "Voyager Golden Record",             1977, "1977",        "NAM", "California","A", "com:Voyager Golden Record cover gold disc|golden record|spacecraft,diagram,launch,render,3d,map"),
    ("skateboard", "Skateboard",                        1965, "c. 1965",     "NAM", "California","A", "com:1960s skateboard vintage clay wheels deck|skateboard|park,rider,logo,modern,shop"),
    ("atari2600",  "Atari 2600",                        1977, "1977",        "NAM", "California","A", "com:Atari 2600 console Evan-Amos|atari 2600,atari-2600|logo,cartridge,advert,box,arcade"),
    ("appleii",    "Apple II",                          1977, "1977",        "NAM", "California","A", "com:Apple II computer museum complete|apple ii|logo,advert,portrait,board only,manual"),
    ("ibmpc",      "IBM Personal Computer",             1981, "1981",        "NAM", "Florida",  "A", "com:IBM PC 5150 computer museum|ibm pc,5150|logo,advert,portrait,board,manual"),
    ("floppy",     "Floppy disk",                       1971, "c. 1971",     "NAM", "California","A", "com:floppy disk 8 inch 5.25 3.5 collection|floppy|drive,icon,logo,art,sculpture"),
    ("postit",     "Post-it note",                      1980, "1980",        "NAM", "Minnesota","A", "com:Post-it note pad yellow adhesive|post-it,postit|wall art,logo,advert,mosaic,crowd"),
    ("airjordan",  "Air Jordan 1",                      1985, "1985",        "NAM", "Oregon",   "A", "com:Air Jordan 1 sneaker 1985 original|air jordan|logo,advert,portrait,store,crowd,box only"),
    ("cokecan",    "Coca-Cola can",                     1960, "1960",        "NAM", "Georgia",  "A", "com:Coca-Cola can vintage steel 1960s|coca-cola can,coke can|bottle,advert,logo,truck,machine,crate"),
    ("n95",        "N95 respirator",                    2020, "2020",        "NAM", "Minnesota","A", "com:N95 respirator mask 3M single|n95,respirator|person wearing,box,pile,factory,diagram,graph"),
    ("ipad",       "iPad",                              2010, "2010",        "NAM", "California","A", "com:iPad first generation 2010 tablet|ipad|logo,advert,person,pro,mini,air,box"),
    ("solarpanel", "Photovoltaic module",               1980, "c. 1980",     "NAM", "California","B", "com:photovoltaic solar module panel single isolated|solar panel,photovoltaic|farm,roof,field,array,diagram,graph,map"),
    ("teslas",     "Tesla Model S",                     2012, "2012",        "NAM", "California","A", "com:Tesla Model S car side view|model s|logo,interior,charging station,crowd,factory,render"),
    ("concorde",   "Concorde",                          1969, "1969",        "EUR", "Anglo-French","A","com:Concorde aircraft museum static side|concorde|flight,cockpit,interior,model,poster,diagram"),
    ("swatch",     "Swatch watch",                      1983, "1983",        "EUR", "Switzerland","A","com:Swatch watch 1980s plastic original|swatch|logo,store,advert,collection wall"),
    ("raspberrypi","Raspberry Pi",                      2012, "2012",        "EUR", "England",  "B", "com:Raspberry Pi model B single board computer|raspberry pi|logo,case,project,robot,cluster"),
    ("arduino",    "Arduino board",                     2005, "2005",        "EUR", "Italy",    "B", "com:Arduino Uno board single|arduino|logo,shield stack,project,breadboard,robot"),
    ("ikeabilly",  "Flat-pack bookcase",                1979, "1979",        "EUR", "Sweden",   "B", "com:IKEA Billy bookcase flat pack|billy,bookcase|store,warehouse,logo,room,shelf full"),
    ("cd",         "Compact Disc",                      1982, "1982",        "EUR", "Netherlands","A","com:compact disc CD single disc underside|compact disc,cd disc|player,drive,logo,stack,art,cover"),
    ("nokia3310",  "Nokia 3310",                        2000, "2000",        "EUR", "Finland",  "A", "com:Nokia 3310 mobile phone|3310|logo,advert,meme,modern,box"),
    ("trinitron",  "Sony Trinitron television",         1968, "1968",        "EAS", "Japan",    "A", "com:Sony Trinitron television set vintage|trinitron|logo,advert,screen shot,modern,shop"),
    ("vhs",        "VHS cassette",                      1976, "1976",        "EAS", "Japan",    "A", "com:VHS video cassette tape single|vhs|player,vcr,shelf,logo,rental,pile"),
    ("tamagotchi", "Tamagotchi",                        1996, "1996",        "EAS", "Japan",    "A", "com:Tamagotchi virtual pet original 1996|tamagotchi|logo,advert,screen,modern,crowd"),
    ("switch",     "Nintendo Switch",                   2017, "2017",        "EAS", "Japan",    "A", "com:Nintendo Switch console Evan-Amos|switch console,nintendo-switch|logo,game,advert,lite,oled,box"),
    ("galaxy",     "Samsung Galaxy",                    2010, "2010",        "EAS", "Korea",    "A", "com:Samsung Galaxy S smartphone 2010|galaxy s|logo,advert,box,modern,fold,note"),
    ("djidrone",   "Consumer quadcopter",               2013, "2013",        "EAS", "China",    "A", "com:DJI Phantom quadcopter drone white|phantom,quadcopter,drone|aerial photo,flight,logo,controller,fpv,racing"),
    ("tr808",      "Roland TR-808",                     1980, "1980",        "EAS", "Japan",    "A", "com:Roland TR-808 drum machine|tr-808,tr808|logo,software,plugin,poster,modern"),
    ("dx7",        "Yamaha DX7",                        1983, "1983",        "EAS", "Japan",    "A", "com:Yamaha DX7 synthesizer keyboard|dx7|logo,software,rack,advert"),
    ("ae1",        "Canon AE-1",                        1976, "1976",        "EAS", "Japan",    "A", "com:Canon AE-1 camera 35mm|ae-1|logo,advert,lens only,modern,strap"),
    ("f91w",       "Casio F-91W",                       1989, "1989",        "EAS", "Japan",    "A", "com:Casio F-91W digital watch|f-91w,f91w|logo,advert,box,modern,wrist"),
    ("shinkansen", "Shinkansen 0 series nose",          1964, "1964",        "EAS", "Japan",    "A", "com:Shinkansen 0 series train museum preserved|0 series,shinkansen|station,platform,crowd,map,diagram,modern,logo"),
    ("lithiumcell","Lithium-ion cell",                  1991, "1991",        "EAS", "Japan",    "B", "com:lithium ion battery cell 18650 single|18650,lithium-ion cell,li-ion cell|pack,car,phone,diagram,graph,fire"),
    ("tatanano",   "Tata Nano",                         2008, "2008",        "SAS", "India",    "B", "com:Tata Nano car side view|nano|logo,interior,factory,crowd,advert"),
    ("jaipurfoot", "Jaipur Foot prosthesis",            1968, "1968",        "SAS", "India",    "B", "com:Jaipur foot prosthetic limb|jaipur foot,prosthe|clinic,patient,portrait,logo,chart"),
    ("mpesa",      "M-Pesa handset",                    2007, "2007",        "AFR", "Kenya",    "B", "com:Nokia 1100 basic mobile phone|1100,1110|logo,advert,box,modern,crowd"),
    ("cochlear",   "Cochlear implant",                  1982, "1982",        "OCE", "Australia","B", "com:cochlear implant device processor|cochlear implant|surgery,diagram,child,logo,scan,graph"),
    ("havaianas",  "Rubber flip-flops",                 1962, "1962",        "LAM", "Brazil",   "B", "com:Havaianas flip flops sandals pair|havaianas,flip-flop,flip flop|beach,store,logo,advert,crowd,feet"),

    # ==========================================================================================
    # THE BALANCE ADDITIONS — 80 rows, authored only after the count below said the first draft of
    # this list was 50% Western against R4's 34% cap. That is the exact failure R4 exists to catch,
    # and it was caught by the number rather than by feel. They are not filler: every one is a
    # named object a collection actually holds, and several are the strongest tier-A picks in the
    # whole list (the Ming banknote, the Marshall Islands stick chart, instant ramen, the Little
    # Red Book). The other half of the correction is the CUT table at the foot of this file.
    # ==========================================================================================

    # ---- E1
    ("ubaid",      "Ubaid lizard-headed figurine",     -4500, "c. 4500 BCE", "WCA", "Iraq",     "C", "com:Ubaid lizard figurine Ur Eridu|ubaid,lizard|map,site,sherd"),
    ("bulla",      "Clay bulla with tokens",           -3300, "c. 3300 BCE", "WCA", "Susa",     "C", "met:clay bulla tokens accounting Susa|bulla,tokens,envelope"),
    ("agroup",     "Nubian A-Group beaker",            -3300, "c. 3300 BCE", "NIL", "Nubia",    "C", "met:Nubian A-Group beaker pottery|beaker,vessel,bowl"),

    # ---- E2
    ("longshan",   "Longshan eggshell cup",            -2500, "c. 2500 BCE", "EAS", "China",    "C", "com:Longshan black pottery eggshell stemmed cup|longshan|map,site,sherd"),
    ("urartu",     "Urartian bronze cauldron",          -700, "c. 700 BCE",  "WCA", "Armenia",  "C", "met:Urartian bronze cauldron attachment|cauldron,bull,attachment"),
    ("shabti",     "Shabti figure",                    -1300, "c. 1300 BCE", "NIL", "Egypt",    "B", "met:shabti figure faience Egypt inscribed|shabti,shawabty,ushabti"),
    ("olmecjade",  "Olmec jade mask",                   -900, "c. 900 BCE",  "AME", "Mexico",   "B", "met:Olmec jade mask Mexico greenstone|mask"),
    ("oxusarmlet", "Achaemenid gold armlet",            -500, "c. 500 BCE",  "WCA", "Persia",   "B", "com:Oxus Treasure gold armlet griffin|armlet,oxus|map,coin,chariot model"),
    ("shangjade",  "Shang jade blade",                 -1300, "c. 1300 BCE", "EAS", "China",    "C", "met:Shang jade blade ceremonial ge|blade,jade,ge"),

    # ---- E3
    ("rhyton",     "Achaemenid rhyton",                 -400, "c. 400 BCE",  "WCA", "Persia",   "B", "met:rhyton gold silver Achaemenid horn|rhyton"),
    ("guptabuddha","Gupta Buddha",                       450, "c. 450 CE",   "SAS", "India",    "B", "met:Gupta period Buddha sandstone India|buddha"),
    ("hanmirror",  "Han bronze mirror",                 -100, "c. 100 BCE",  "EAS", "China",    "C", "met:Han bronze mirror TLV Chinese|mirror"),
    ("hanlacquer", "Han lacquer cup",                   -100, "c. 100 BCE",  "EAS", "China",    "C", "met:Han lacquer eared cup winged|cup,bowl,box"),
    ("zapotec",    "Zapotec effigy urn",                 400, "c. 400 CE",   "AME", "Oaxaca",   "C", "art:Zapotec effigy vessel urn Oaxaca|urn,vessel,effigy"),
    ("funangold",  "Óc Eo gold plaque",                  400, "c. 400 CE",   "SEA", "Mekong",   "C", "com:Oc Eo gold plaque Funan archaeology|oc eo|map,site,plan"),
    ("djennejeno", "Djenné-jeno terracotta",             400, "c. 400 CE",   "AFR", "Mali",     "C", "com:Djenne-jeno terracotta figure Mali|djenne,jenne|map,mosque,town,aerial"),
    ("yemenstele", "South Arabian stele",                100, "c. 100 CE",   "WCA", "Yemen",    "C", "met:South Arabian alabaster stele Yemen head|stele,head,funerary"),

    # ---- E4
    ("chinesenote","Ming paper money",                  1375, "1375",        "EAS", "China",    "A", "com:Ming dynasty banknote Da Ming Baochao|banknote,baochao,paper money|modern,yuan,coin,map"),
    ("songding",   "Song bronze vessel",                1100, "c. 1100",     "EAS", "China",    "C", "met:Song dynasty bronze ding vessel archaistic|ding,vessel,censer"),
    ("mongolbow",  "Composite bow",                     1250, "c. 1250",     "EAS", "Mongolia", "B", "met:composite bow Asian horn sinew|bow"),
    ("prayerwheel","Tibetan prayer wheel",              1400, "c. 1400",     "EAS", "Tibet",    "B", "met:Tibetan prayer wheel mani|prayer wheel,wheel"),
    ("quranfolio", "Kufic Qur'an folio",                1000, "c. 1000",     "WCA", "Abbasid",  "B", "met:Kufic Quran folio parchment calligraphy|folio,leaf,quran"),
    ("baptistere", "Mamluk inlaid basin",               1330, "c. 1330",     "WCA", "Syria",    "B", "met:Mamluk brass basin inlaid silver|basin,bowl"),
    ("hoysala",    "Hoysala temple sculpture",          1200, "c. 1200",     "SAS", "India",    "C", "met:Hoysala sculpture stone Karnataka deity|sculpture,figure,deity,celestial"),
    ("champa",     "Cham sandstone sculpture",          1000, "c. 1000",     "SEA", "Vietnam",  "C", "met:Cham sandstone sculpture Vietnam|cham,figure,deity,head"),
    ("aztecserpent","Aztec double-headed serpent",      1450, "c. 1450",     "AME", "Mexica",   "A", "com:Aztec double-headed serpent turquoise mosaic British Museum|serpent|calendar,stone,codex,map,pyramid"),
    ("tainozemi",  "Taíno zemí",                        1400, "c. 1400",     "AME", "Caribbean","C", "met:Taino zemi stone Caribbean|zemi,figure,stone"),

    # ---- E5
    ("batik",      "Javanese batik cloth",              1750, "c. 1750",     "SEA", "Java",     "B", "met:batik cloth Java Indonesia wax resist|batik,sarong,skirt"),
    ("wayang",     "Wayang kulit puppet",               1700, "c. 1700",     "SEA", "Java",     "B", "met:wayang kulit shadow puppet Java|puppet,wayang"),
    ("burmalacquer","Burmese lacquer box",              1750, "c. 1750",     "SEA", "Burma",    "C", "met:Burmese lacquer betel box vessel|box,vessel,lacquer"),
    ("chiwara",    "Chi wara headdress",                1800, "c. 1800",     "AFR", "Mali",     "B", "met:Chi wara headdress Bamana antelope|chi wara,headdress,antelope"),
    ("asantestool","Asante stool",                      1700, "c. 1700",     "AFR", "Ghana",    "B", "art:Asante stool wood Ghana|stool"),
    ("jebena",     "Ethiopian coffee pot",              1750, "c. 1750",     "AFR", "Ethiopia", "C", "com:jebena Ethiopian coffee pot clay|jebena|ceremony,cafe,person,beans"),
    ("tipustiger", "Tipu's Tiger",                      1795, "c. 1795",     "SAS", "Mysore",   "A", "com:Tipu's Tiger Victoria Albert Museum automaton|tipu|portrait,painting,fort,map"),
    ("katar",      "Katar dagger",                      1650, "c. 1650",     "SAS", "India",    "C", "met:katar dagger Indian punch|katar,dagger"),
    ("sitar",      "Sitar",                             1750, "c. 1750",     "SAS", "India",    "B", "met:sitar Indian stringed instrument|sitar"),
    ("qero",       "Andean qero cup",                   1650, "c. 1650",     "AME", "Peru",     "C", "art:qero cup Inca colonial wood painted|qero,kero,cup,beaker"),
    ("snowgoggles","Inuit snow goggles",                1750, "c. 1750",     "AME", "Arctic",   "A", "com:Inuit snow goggles ivory slit wooden|snow goggles|modern,ski,sunglasses,diagram"),
    ("matecalabash","Mate gourd and bombilla",          1750, "c. 1750",     "LAM", "Río de la Plata","B","com:mate gourd silver bombilla antique|mate,bombilla|drink,cafe,plant,leaves,modern"),
    ("stickchart", "Marshall Islands stick chart",      1800, "c. 1800",     "OCE", "Marshall Is.","A","com:Marshall Islands stick chart navigation|stick chart,rebbelib|map,modern,satellite,atoll"),
    ("samovar",    "Samovar",                           1800, "c. 1800",     "WCA", "Persia",   "B", "met:samovar brass tea urn|samovar,urn"),

    # ---- E6
    ("hanafuda",   "Hanafuda cards",                    1889, "1889",        "EAS", "Japan",    "B", "com:hanafuda playing cards Japanese flower|hanafuda|logo,advert,screen,modern box"),
    ("kimono",     "Meiji kimono",                      1880, "c. 1880",     "EAS", "Japan",    "B", "met:kimono Japanese silk Meiji robe|kimono,robe"),
    ("abacus",     "Suanpan abacus",                    1850, "c. 1850",     "EAS", "China",    "B", "com:suanpan Chinese abacus wooden beads|abacus,suanpan|diagram,modern plastic,shop,logo"),
    ("pekingmask", "Peking opera headdress",            1880, "c. 1880",     "EAS", "China",    "C", "met:Peking opera headdress Chinese theatrical|headdress,crown,mask"),
    ("bidri",      "Bidri water vessel",                1850, "c. 1850",     "SAS", "Deccan",   "C", "met:bidri vessel inlaid silver Deccan|bidri,vessel,huqqa,ewer"),
    ("bogolan",    "Bogolan mud cloth",                 1880, "c. 1880",     "AFR", "Mali",     "C", "art:bogolanfini mud cloth Mali textile|cloth,bogolan,textile"),
    ("mbira",      "Mbira",                             1890, "c. 1890",     "AFR", "Zimbabwe", "B", "met:mbira thumb piano lamellophone Africa|mbira,sanza,lamellophone"),
    ("djembe",     "Djembe drum",                       1880, "c. 1880",     "AFR", "West Africa","B","met:djembe drum West African goblet|drum,djembe"),
    ("birchcanoe", "Birchbark canoe",                   1850, "c. 1850",     "AME", "Great Lakes","A","com:birchbark canoe museum Ojibwe model|birchbark,birch bark canoe|river,lake,people,modern,map"),
    ("chilkat",    "Chilkat blanket",                   1880, "c. 1880",     "AME", "Tlingit",  "B", "art:Chilkat blanket Tlingit dancing robe|chilkat,blanket,robe"),
    ("panamahat",  "Montecristi straw hat",             1880, "c. 1880",     "LAM", "Ecuador",  "A", "com:Panama hat Montecristi straw toquilla|panama hat,toquilla|worker,canal,portrait,shop,brand"),
    ("didgeridoo", "Didgeridoo",                        1880, "c. 1880",     "OCE", "Arnhem Land","A","com:didgeridoo yidaki wooden instrument museum|didgeridoo,yidaki|player,performance,shop,tourist"),
    ("karagoz",    "Karagöz shadow puppet",             1850, "c. 1850",     "WCA", "Ottoman",  "C", "com:Karagoz shadow puppet Ottoman leather|karagöz,karagoz|theatre,poster,modern,book"),

    # ---- E7
    ("instantramen","Instant ramen packet",             1958, "1958",        "EAS", "Japan",    "A", "com:Chikin Ramen 1958 instant noodle package museum|chikin ramen,instant ramen|bowl,cooked,cup,shop,logo"),
    ("ricecooker", "Automatic rice cooker",             1955, "1955",        "EAS", "Japan",    "A", "com:Toshiba automatic rice cooker 1955 electric|rice cooker|modern,logo,advert,open lid"),
    ("flyingpigeon","Flying Pigeon bicycle",            1950, "c. 1950",     "EAS", "China",    "B", "com:Flying Pigeon bicycle Chinese black roadster|flying pigeon,feige|crowd,street,logo,modern,shop"),
    ("enamelmug",  "Enamel mug",                        1955, "c. 1955",     "EAS", "China",    "C", "com:Chinese enamel mug slogan vintage|enamel mug,enamelware|modern,camping,set,shop"),
    ("godrej",     "Steel almirah",                     1930, "c. 1930",     "SAS", "India",    "C", "com:Godrej steel almirah cupboard vintage|almirah,godrej|logo,advert,factory,showroom"),
    ("sari",       "Handloom sari",                     1950, "c. 1950",     "SAS", "India",    "B", "met:sari silk handloom India woven|sari,saree,textile"),
    ("adire",      "Adire indigo cloth",                1930, "c. 1930",     "AFR", "Nigeria",  "C", "art:adire indigo resist dyed cloth Yoruba|adire,cloth,textile,wrapper"),
    ("talkingdrum","Talking drum",                      1930, "c. 1930",     "AFR", "Nigeria",  "C", "met:talking drum hourglass pressure African|drum"),
    ("luchamask",  "Lucha libre mask",                  1940, "c. 1940",     "LAM", "Mexico",   "A", "com:lucha libre mask museum collection wrestling|lucha,mask|wrestler,ring,crowd,poster,shop"),
    ("hillshoist", "Rotary clothes hoist",              1945, "1945",        "OCE", "Australia","B", "com:Hills Hoist rotary clothes line|hills hoist,rotary clothes|backyard,house,modern,logo"),
    ("ute",        "Coupé utility",                     1934, "1934",        "OCE", "Australia","B", "com:Ford coupe utility 1934 Australia ute|coupe utility,ute|modern,logo,advert,race"),
    ("keffiyeh",   "Keffiyeh",                          1930, "c. 1930",     "WCA", "Levant",   "B", "com:keffiyeh kufiya cloth folded textile museum|keffiyeh,kufiya|protest,crowd,portrait,flag,fashion"),

    # ---- E8
    ("hellokitty", "Hello Kitty coin purse",            1974, "1974",        "EAS", "Japan",    "A", "com:Hello Kitty vintage 1970s coin purse toy|hello kitty|store,logo,cafe,crowd,cosplay"),
    ("pokemoncard","Pokémon trading card",              1996, "1996",        "EAS", "Japan",    "A", "com:Pokemon trading card 1996 base set|pokemon card|logo,game,plush,crowd,set"),
    ("karaoke",    "Karaoke machine",                   1971, "1971",        "EAS", "Japan",    "A", "com:karaoke machine 8-track vintage Japanese|karaoke|bar,crowd,screen,app,logo"),
    ("seikoquartz","Quartz wristwatch",                 1969, "1969",        "EAS", "Japan",    "A", "com:Seiko Astron 1969 quartz watch|astron,seiko quartz|logo,advert,modern,diagram"),
    ("corolla",    "Toyota Corolla",                    1966, "1966",        "EAS", "Japan",    "A", "com:Toyota Corolla 1966 first generation car|corolla|logo,interior,modern,factory,advert"),
    ("redbook",    "Quotations from Chairman Mao",      1964, "1964",        "EAS", "China",    "A", "com:Little Red Book Quotations Chairman Mao copy|little red book,quotations|crowd,rally,poster,portrait,statue"),
    ("hyundaipony","Hyundai Pony",                      1975, "1975",        "EAS", "Korea",    "B", "com:Hyundai Pony 1975 car museum|pony|logo,modern,factory,rally,interior"),
    ("kpopstick",  "Concert lightstick",                2015, "c. 2015",     "EAS", "Korea",    "B", "com:kpop lightstick official concert|lightstick,light stick|crowd,concert,ocean,logo,fan"),
    ("byd",        "Chinese electric car",              2022, "2022",        "EAS", "China",    "B", "com:BYD electric car side view|byd|logo,factory,charging,interior,crowd,show"),
    ("wiimote",    "Wii Remote",                        2006, "2006",        "EAS", "Japan",    "A", "com:Wii Remote controller Evan-Amos|wii remote,wiimote|console,logo,game,advert,crowd"),
    ("bajaj",      "Auto rickshaw",                     1972, "c. 1972",     "SAS", "India",    "B", "com:Bajaj auto rickshaw three wheeler|auto rickshaw,bajaj|street,traffic,crowd,logo,e-rickshaw"),
    ("solarlantern","Solar lantern",                    2010, "c. 2010",     "AFR", "Kenya",    "B", "com:solar lantern portable off-grid lamp|solar lantern,solar lamp|village,child,chart,map,farm,array"),
    ("papunya",    "Papunya board",                     1971, "1971",        "OCE", "Australia","B", "com:Papunya Tula early painting board Western Desert|papunya|gallery,map,artist,canvas"),
    ("embraer",    "Regional jet",                      1996, "1996",        "LAM", "Brazil",   "B", "com:Embraer ERJ 145 aircraft side view|erj,embraer|logo,cockpit,interior,factory,flight,model"),
]


# The 72 sourced in passes 1-4 predate this ticket's buckets and tiers. Assigned here, by the same
# rules, so the coverage table measures ONE set and not two. `aldrin` is dropped by R1 (no
# identifiable person as the falling object) and is recorded in the exclusions, not silently gone.
EXISTING = {
 "ainghazal":("WCA","B"), "jomon":("EAS","B"), "jar":("WCA","C"), "worshiper":("WCA","C"),
 "cuneiform":("WCA","B"), "indus":("SAS","B"), "hippo":("NIL","B"), "nebra":("EUR","A"),
 "tutmask":("NIL","A"), "gu":("EAS","C"), "olmec":("AME","A"), "kouros":("EUR","B"),
 "corinth":("EUR","B"), "amphora":("EUR","B"), "krater":("EUR","B"), "terracotta":("EAS","A"),
 "buddha":("SAS","B"), "haniwa":("EAS","C"), "moche":("AME","C"), "tanghorse":("EAS","B"),
 "mayavessel":("AME","C"), "nataraja":("SAS","B"), "ewer":("WCA","C"), "astrolabe":("WCA","B"),
 "chalice":("EUR","C"), "chimu":("AME","C"), "mosquelamp":("WCA","C"), "ming":("EAS","A"),
 "crossbow":("EUR","B"), "katana":("EAS","B"), "benin":("AFR","A"), "tableclock":("EUR","B"),
 "telescope":("EUR","A"), "armor":("EUR","B"), "stradivari":("EUR","A"), "dogon":("AFR","C"),
 "samurai":("EAS","A"), "netsuke":("EAS","C"), "rocket":("EUR","A"), "colt":("NAM","A"),
 "pennyfarthing":("EUR","A"), "typewriter":("NAM","A"), "phone":("NAM","A"), "bulb":("NAM","A"),
 "kubamask":("AFR","B"), "flyer":("NAM","A"), "modelt":("NAM","A"), "cokebottle":("NAM","A"),
 "leica":("EUR","A"), "camera":("NAM","B"), "enigma":("EUR","A"), "vespa":("EUR","A"),
 "vinyl":("NAM","A"), "rotaryphone":("NAM","A"), "lego":("EUR","A"), "cassette":("EUR","A"),
 "chip":("NAM","A"), "polaroid":("NAM","A"), "rubik":("EUR","A"), "walkman":("EAS","A"),
 "dynatac":("NAM","A"), "mac":("NAM","A"), "nes":("EAS","A"), "gameboy":("EAS","A"),
 "neogeo":("EAS","A"), "playstation":("EAS","A"), "boombox":("EAS","A"), "imac":("NAM","A"),
 "ipod":("NAM","A"), "iphone":("NAM","A"), "vaccine":("EUR","A"),
}

# ---------------------------------------------------------------------------------------------
# BALANCE PASS, before a single image was fetched. The first draft of this list measured 50%
# Western against R4's 34% cap — the exact failure R4 exists to catch, caught by the number and
# not by feel. Two corrections, in this order: cut the weakest Western candidates (below), then
# author 80 more non-Western ones (further below). Cut rows are LEFT IN PLACE, not deleted, so the
# ticket's "deliberately excluded" list is the record itself rather than a memory of it.
CUT = {
 # redundant with a stronger candidate already in the list
 "cucuteni":"third Old-European figurine/vessel in E1; vinca + varna carry it",
 "celglobe2":"second European globe; mercator is the stronger one",
 "venetianglass":"third European glass object; delft and stainedglass cover it",
 "romanglass":"Roman material already carried by helmet, gladius, vindolanda",
 "pompeiilamp":"same",
 "meissen":"European porcelain duplicated by delft",
 "delft":"kept meissen out instead — one of the two, and neither is recognisable",
 "brownbess":"third European firearm before 1800 with wheellock already in",
 "gundestrup":"third European metalwork in E3",
 "varna":"second E1 European gold",
 "oseberg":"Viking material thin on cut-outable objects; sutton carries northern Europe",
 "sextant":"navigation already carried by h4 and mercator",
 "pocketwatch":"horology already carried by tableclock and h4",
 "gatling":"third US firearm with colt and winchester in",
 "ibmpc":"third US home computer of 1977-81 with appleii and atari2600 in",
 "cokecan":"cokebottle is already in the set",
 "slinky":"US post-war toy already carried by monopoly",
 "tupperware":"weak silhouette and weak recognition against the same era's stronger picks",
 "masonjar":"same",
 "cornflakes":"a package, not a made object with a body",
 "windsor":"furniture with no recognition value at this scale",
 "citroen2cv":"fourth European car; mini, vwbeetle and benz carry it",
 "ikeabilly":"flat-pack reads as furniture, not as the idea",
 "arduino":"second European single-board computer; raspberrypi is more recognisable",
 "teslacoil":"reads as apparatus, not as an object anyone names",
 "xraytube":"same",
 "marconi":"same",
 "dieselengine":"same",
 "wassily":"second Bauhaus object; wagenfeld carries it",
 "anglepoise":"third European lamp",
 "claypipe":"no recognition and no fragment legibility",
 "morsekey2":"failed in pass 4 as scattered parts; not worth a second attempt",
 "solarpanel":"a flat rectangle — outline-only, and it is not tier A, so R2 excludes it",
 "teslas":"fifth car in the set and the newest, weakest silhouette",
 "ipad":"iphone is already in; a second Apple slab adds nothing",
}
